language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: RfudPqBCn9EIdE0hpI5dcL0vCjkje6t6C0J37Bk5nJB+LKEIP8T+3f3AgHhhpfPnpCciUOpujBEQACHBv3X8UF8LfTM7jMsSJVHgCzk9YagI2TppkSyaD1dIsr1HApTB+yPSkQLzHKvmFiDSIPnLOpQeB5p1h4Q/IbcAEBVpDyBeL50C0204MkDL1iozC70e4zF0n4rgKd2V6r/rsODtI6fRD4NnlVOnCzc5QP69mHqIn2TV8O/wDDLmsErpVA6b0wVVOfRZQhpkPbcxboj5Owt7Rtnc7zwx9Lhr+oH6s/3y4V1zH4WsrdRJOR8JgUGtsGmInr16AERZvQvPGgELaAgJFe9j4PbVauouFbBIqDtmlKjFXgO/jfmf2RVNyyx3g6mB/22LOhjV+RwEd0jergXr043hgLMtM6GXF+iw+DqtFss34jj5+vygErawB4P9EDUiAyj5oFa/geBGX3/NNfM89UP5sa/ecZFQRtFMRObRmvYzi/WPiSlacMKOYHZw0LpdW4Rc69iBCXwbKIEgNvNpwihJiM50neITQxc9tJAdEtYCdscva3OezKa0QYMYwaVqI10WGxuBNpFpFVux/ml1Ad2qs5Qc5Ee0X5TcxkOP8d5iAn8AXihsLLm1ONuyvjqtVHypy5VDNaesqHur9/AgItPhlqzMTdBDDIckNUI=
  app: cv-palette-picker
  skip_cleanup: true
